-- Seed default templates for each page type
insert into public.seo_templates (
  page_type, name, is_default,
  title_template_ar, title_template_en,
  meta_description_ar, meta_description_en,
  h1_template_ar, h1_template_en,
  intro_template_ar, intro_template_en,
  canonical_pattern, default_content_mode,
  body_sections_ar, body_sections_en, faq_template
) values
-- ─── City template ───
('city', 'قالب المدينة الافتراضي', true,
  '{{name_ar}} — فرص تطوير عقاري وشراكات استثمارية | سينا',
  '{{name_en}} — Real Estate Development & Partnership Opportunities | SINA',
  'استعرض أبرز الفرص العقارية للتطوير والشراكة في {{name_ar}} عبر منصة سينا المرخّصة. بيانات موثّقة، تواصل آمن، وحوكمة كاملة.',
  'Browse premium real estate development and partnership opportunities in {{name_en}} on SINA — licensed, verified data, secure communication, full governance.',
  'الفرص العقارية في {{name_ar}}',
  'Real Estate Opportunities in {{name_en}}',
  'تعرّف على أبرز الأراضي والمشاريع العقارية المتاحة للشراكة التطويرية في {{name_ar}}، بهيكل شراكة شفاف يحفظ حقوق المالك والمطور.',
  'Discover the most promising lands and real estate projects available for development partnership in {{name_en}}, with transparent deal structures that protect both owners and developers.',
  '/sa/{{slug}}', 'auto_review',
  '[{\"heading_ar\":\"نظرة على سوق {{name_ar}}\",\"body_ar\":\"تحتضن مدينة {{name_ar}} فرصاً عقارية متنوعة تغطي الأراضي والمشاريع السكنية والتجارية، وتتميّز بحركة نمو عمراني نشطة.\"},{\"heading_ar\":\"فرص التطوير العقاري\",\"body_ar\":\"منصة سينا توفّر بيئة رقمية منظمة تربط ملاك الأراضي بالمطورين المؤهلين، مع تحقق متعدد المراحل وخصوصية كاملة.\"}]'::jsonb,
  '[{\"heading_en\":\"Market Overview of {{name_en}}\",\"body_en\":\"{{name_en}} hosts a diverse portfolio of real estate opportunities covering lands and residential/commercial projects, characterized by active urban growth.\"},{\"heading_en\":\"Development Opportunities\",\"body_en\":\"SINA provides an organized digital environment connecting landowners with qualified developers, with multi-stage verification and full privacy.\"}]'::jsonb,
  '[{\"question_ar\":\"كيف أجد فرصة عقارية في {{name_ar}}؟\",\"answer_ar\":\"أنشئ حساباً على سينا وتصفّح الفرص المتاحة، أو أدرج أرضك لاستقبال عروض شراكة من مطورين معتمدين.\",\"question_en\":\"How do I find a real estate opportunity in {{name_en}}?\",\"answer_en\":\"Create an account on SINA and browse available opportunities, or list your land to receive partnership offers from verified developers.\"}]'::jsonb
),
-- ─── Property Type template ───
('property_type', 'قالب نوع العقار الافتراضي', true,
  '{{name_ar}} — فرص استثمار وتطوير | سينا',
  '{{name_en}} — Investment & Development Opportunities | SINA',
  'استعرض فرص {{name_ar}} للتطوير والشراكة العقارية في المملكة العربية السعودية عبر منصة سينا.',
  'Browse {{name_en}} development and partnership opportunities across Saudi Arabia on SINA.',
  '{{name_ar}} — فرص التطوير والاستثمار',
  '{{name_en}} — Development & Investment Opportunities',
  'دليلك للفرص المتاحة في قطاع {{name_ar}} في السوق السعودي، من أراضٍ جاهزة للتطوير إلى مشاريع شراكة منظّمة.',
  'Your guide to available opportunities in the {{name_en}} sector in the Saudi market — from ready-to-develop lands to structured partnership projects.',
  '/properties/{{slug}}', 'auto_review',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb
),
-- ─── Service template ───
('service', 'قالب الخدمة الافتراضي', true,
  '{{name_ar}} | سينا — منصة عقارية سعودية',
  '{{name_en}} | SINA — Saudi Real Estate Platform',
  'خدمات {{name_ar}} عبر منصة سينا — بيئة منظمة، مطورون معتمدون، وحوكمة كاملة لكل صفقة.',
  '{{name_en}} services via SINA — regulated environment, verified developers, full governance per deal.',
  '{{name_ar}}',
  '{{name_en}}',
  'اكتشف كيف تقدّم منصة سينا خدمات {{name_ar}} باحترافية عالية وبنية تنظيمية مطابقة لأنظمة المملكة.',
  'Discover how SINA delivers {{name_en}} services with high professionalism and a regulatory structure compliant with Saudi law.',
  '/services/{{slug}}', 'auto_review',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb
),
-- ─── Topic template (informational, mostly manual/review) ───
('topic', 'قالب الموضوع الافتراضي', true,
  '{{name_ar}} — دليل سينا',
  '{{name_en}} — SINA Guide',
  'تعرّف على {{name_ar}} في السوق العقاري السعودي: المفهوم، الأنظمة، وكيف يعمل في الواقع عبر منصة سينا.',
  'Learn about {{name_en}} in the Saudi real estate market: concept, regulations, and how it works in practice on SINA.',
  '{{name_ar}}',
  '{{name_en}}',
  'دليل معرفي شامل حول {{name_ar}} يساعدك على فهم الأساسيات وأفضل الممارسات.',
  'A comprehensive guide to {{name_en}} helping you understand the essentials and best practices.',
  '/topics/{{slug}}', 'manual_only',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb
),
-- ─── Developer template ───
('developer', 'قالب المطور الافتراضي', true,
  '{{company_name}} — ملف المطور العقاري | سينا',
  '{{company_name}} — Real Estate Developer Profile | SINA',
  'ملف {{company_name}} على منصة سينا: المشاريع، المدن المستهدفة، وحالة التحقق من السجل التجاري.',
  '{{company_name}} profile on SINA: projects, target cities, and commercial registry verification status.',
  '{{company_name}}',
  '{{company_name}}',
  'تعرّف على {{company_name}} وتفاصيل عمله التطويري عبر منصة سينا العقارية.',
  'Learn about {{company_name}} and their development activity on SINA real estate platform.',
  '/developers/{{slug}}', 'auto_review',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb
),
-- ─── Company template (same as developer but distinct bucket) ───
('company', 'قالب الشركة الافتراضي', true,
  '{{company_name}} — شركة عقارية | سينا',
  '{{company_name}} — Real Estate Company | SINA',
  '{{company_name}} ضمن شبكة الشركات العقارية الموثّقة على منصة سينا.',
  '{{company_name}} — part of SINA''s verified real estate company network.',
  '{{company_name}}',
  '{{company_name}}',
  'نظرة على {{company_name}} كشركة عقارية ضمن منصة سينا.',
  'An overview of {{company_name}} as a real estate company within the SINA platform.',
  '/companies/{{slug}}', 'auto_review',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb
),
-- ─── District template ───
('district', 'قالب الحي الافتراضي', true,
  'حي {{name_ar}} — {{parent_name_ar}} | فرص عقارية | سينا',
  '{{name_en}} District — {{parent_name_en}} | SINA',
  'فرص التطوير والشراكة العقارية في حي {{name_ar}} بمدينة {{parent_name_ar}} عبر منصة سينا.',
  'Real estate development and partnership opportunities in {{name_en}} district, {{parent_name_en}}, via SINA.',
  'الفرص العقارية في حي {{name_ar}}',
  'Real Estate Opportunities in {{name_en}} District',
  'حي {{name_ar}} في {{parent_name_ar}} — لمحة عن الفرص العقارية والأراضي المتاحة للتطوير.',
  '{{name_en}} district in {{parent_name_en}} — snapshot of available real estate and development opportunities.',
  '/sa/{{parent_slug}}/{{slug}}', 'auto_review',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb
),
-- ─── Hybrid template (Service × City) ───
('hybrid', 'قالب الخدمة × المدينة', true,
  '{{service_ar}} في {{city_ar}} | سينا',
  '{{service_en}} in {{city_en}} | SINA',
  '{{service_ar}} في {{city_ar}} عبر منصة سينا — بيانات موثّقة، مطورون معتمدون، وبيئة تنظيمية منظمة.',
  '{{service_en}} in {{city_en}} via SINA — verified data, certified developers, regulated environment.',
  '{{service_ar}} في {{city_ar}}',
  '{{service_en}} in {{city_en}}',
  'دليلك لخدمات {{service_ar}} في مدينة {{city_ar}} عبر منصة سينا العقارية.',
  'Your guide to {{service_en}} in {{city_en}} via the SINA real estate platform.',
  '/services/{{service_slug}}/sa/{{city_slug}}', 'auto_review',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb
);

-- Seed default generation rules
insert into public.seo_generation_rules (name, page_type, min_data_requirements, quality_gates, max_pages_per_run, content_mode, priority) values
  ('City pages — all active cities', 'city',
    '{\"min_name_length\": 2}'::jsonb,
    '{\"min_word_count\": 250, \"require_internal_links\": 2, \"max_title_length\": 70, \"max_description_length\": 160}'::jsonb,
    20, 'auto_review', 100),
  ('Property type pages', 'property_type',
    '{}'::jsonb,
    '{\"min_word_count\": 200, \"require_internal_links\": 2}'::jsonb,
    20, 'auto_review', 90),
  ('Service pages — non-sensitive', 'service',
    '{\"exclude_sensitive\": true}'::jsonb,
    '{\"min_word_count\": 250, \"require_faq\": false}'::jsonb,
    20, 'auto_review', 80),
  ('Service pages — sensitive (financing, funds, white-land-fees)', 'service',
    '{\"only_sensitive\": true}'::jsonb,
    '{\"min_word_count\": 500, \"require_faq\": true}'::jsonb,
    20, 'manual_only', 85),
  ('Topic pages — all manual', 'topic',
    '{}'::jsonb,
    '{\"min_word_count\": 600, \"require_faq\": true, \"require_internal_links\": 3}'::jsonb,
    10, 'manual_only', 70),
  ('Developer pages — verified only', 'developer',
    '{\"verification_status\": \"verified\"}'::jsonb,
    '{\"min_word_count\": 150}'::jsonb,
    50, 'auto_review', 60),
  ('Hybrid: Service × City', 'hybrid',
    '{\"require_city\": true, \"require_service\": true}'::jsonb,
    '{\"min_word_count\": 300, \"require_internal_links\": 3}'::jsonb,
    30, 'auto_review', 50);
